name = "next-website-yukue"
compatibility_date = "2025-07-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# アカウントIDが必要な場合はここに追加
# account_id = "your-account-id"

[env.production]
name = "next-website-yukue-production"

[env.preview]
name = "next-website-yukue-preview"
